/*
 * This is the wrapper (JFrame) that contains all menus and panels.
 */
package wtc;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import static wtc.WTC.activeCardName;
import static wtc.WTC.intNewPanelName;
import static wtc.WTC.itemName;
import static wtc.WTC.strNewPanelName;

/**
 *
 * @author Jean-Luc Poissonnet alias Dreamzor
 */
public class mainFrame extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width-this.getSize().width-5, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel = new javax.swing.JPanel();
        jPanelEmpty = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuConfig = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuTrades = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wraeclast Trading Company");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(300, 150));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(300, 150));

        cardsPanel.setBackground(new java.awt.Color(102, 102, 102));
        cardsPanel.setLayout(new java.awt.CardLayout());

        jPanelEmpty.setBackground(new java.awt.Color(102, 102, 102));
        jPanelEmpty.setMaximumSize(new java.awt.Dimension(300, 130));
        jPanelEmpty.setMinimumSize(new java.awt.Dimension(300, 130));
        jPanelEmpty.setName("-1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wraeclast Trading Company");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Currently no trade");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(This window will popup on trade request)");

        javax.swing.GroupLayout jPanelEmptyLayout = new javax.swing.GroupLayout(jPanelEmpty);
        jPanelEmpty.setLayout(jPanelEmptyLayout);
        jPanelEmptyLayout.setHorizontalGroup(
            jPanelEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyLayout.createSequentialGroup()
                .addGroup(jPanelEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmptyLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2))
                    .addGroup(jPanelEmptyLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanelEmptyLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelEmptyLayout.setVerticalGroup(
            jPanelEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        cardsPanel.add(jPanelEmpty, "-1");

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(300, 20));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(300, 20));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(300, 20));
        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setToolTipText("");
        jMenu.setActionCommand("Menu");
        jMenu.setLabel("Menu");

        jMenuConfig.setBackground(new java.awt.Color(51, 51, 51));
        jMenuConfig.setForeground(new java.awt.Color(255, 255, 255));
        jMenuConfig.setText("Configuration");
        jMenuConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfigActionPerformed(evt);
            }
        });
        jMenu.add(jMenuConfig);

        jMenuExit.setBackground(new java.awt.Color(51, 51, 51));
        jMenuExit.setForeground(new java.awt.Color(255, 255, 255));
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu.add(jMenuExit);

        jMenuBar1.add(jMenu);

        jMenuTrades.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTrades.setText("Trades (0)");
        jMenuBar1.add(jMenuTrades);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jMenuBar1MousePressed

    private void jMenuConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfigActionPerformed
            new optionFrame().setVisible(true);
    }//GEN-LAST:event_jMenuConfigActionPerformed

    private void menuItemActionPerformed(ActionEvent evt){
        activeCardName = ((JMenuItem) evt.getSource()).getName();
        CardLayout c1 = (CardLayout)(cardsPanel.getLayout());
        c1.show(cardsPanel, activeCardName);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                              
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);    
            }
        });
    }

    public void addCard() {
        CardLayout c1 = (CardLayout)(cardsPanel.getLayout());
        Component[] components = cardsPanel.getComponents();
        jMenuTrades.setText("Trades (" + Integer.toString(components.length) + ")");
        JPanel newCard = new tradeJPanel();
        
        if (components.length == 1) {
            strNewPanelName = "0";
            newCard.setName(strNewPanelName);
            cardsPanel.add(newCard, "0");
            
            //Show only first trade
            c1.show(cardsPanel, "0");
            activeCardName = "0";
        }
        else{
            //Get the highest card name
            int max = Integer.parseInt(components[0].getName());

            for (int i = 1; i < components.length; i++) {
                if (Integer.parseInt(components[i].getName()) > max) {
                  max = Integer.parseInt(components[i].getName());
                }
            }
            //Name the new card
            intNewPanelName = max + 1;
            strNewPanelName = Integer.toString(intNewPanelName);
            newCard.setName(strNewPanelName);
                        
            //Add the new panel to container & list
            cardsPanel.add(newCard, strNewPanelName);
        }
        
        //Add item in Trade menu
        JMenuItem tradeMenuItem = new JMenuItem(itemName);
        tradeMenuItem.setName(strNewPanelName);
        tradeMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        tradeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        tradeMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActionPerformed(evt);
            }
        });
        jMenuTrades.add(tradeMenuItem);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel cardsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConfig;
    private javax.swing.JMenuItem jMenuExit;
    public static javax.swing.JMenu jMenuTrades;
    private javax.swing.JPanel jPanelEmpty;
    // End of variables declaration//GEN-END:variables
}
